/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param body 
 * @param title 
 * @param userID 
 */


data class CommonSendNotificationIn (

    @Json(name = "body")
    val body: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "userID")
    val userID: kotlin.Int

)

