/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param partyID 
 */


data class CommonAddListToEventIn (

    @Json(name = "name")
    val name: CommonAddListToEventIn.Name,

    @Json(name = "partyID")
    val partyID: kotlin.Int

) {

    /**
     * 
     *
     * Values: eMPTY,tODO,bUY,wISHLIST,unknownDefaultOpenApi
     */
    @JsonClass(generateAdapter = false)
    enum class Name(val value: kotlin.String) {
        @Json(name = "EMPTY") eMPTY("EMPTY"),
        @Json(name = "TODO") tODO("TODO"),
        @Json(name = "BUY") bUY("BUY"),
        @Json(name = "WISHLIST") wISHLIST("WISHLIST"),
        @Json(name = "unknown_default_open_api") unknownDefaultOpenApi("unknown_default_open_api");
    }
}

