/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param expenseForUser 
 * @param userDebt 
 * @param userDebtString 
 */


data class CommonCalculateExpensesOut (

    @Json(name = "expenseForUser")
    val expenseForUser: kotlin.String,

    @Json(name = "userDebt")
    val userDebt: kotlin.Double,

    @Json(name = "userDebtString")
    val userDebtString: kotlin.String

)

