/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param coverID 
 * @param isManager 
 * @param isNew 3 дня после создания
 * @param name 
 * @param partyID 
 */


data class CommonGetUserPartiesOut (

    @Json(name = "coverID")
    val coverID: kotlin.Int,

    @Json(name = "isManager")
    val isManager: kotlin.Boolean,

    /* 3 дня после создания */
    @Json(name = "isNew")
    val isNew: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "partyID")
    val partyID: kotlin.Int

)

