/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param listID 
 * @param tasks 
 */


data class CommonAddTasksToListIn (

    @Json(name = "listID")
    val listID: kotlin.Int,

    @Json(name = "tasks")
    val tasks: kotlin.collections.List<CommonTaskCreateIn>

)

