/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models

import com.github.linkav20.network.data.models.CommonTaskInfo

import com.squareup.moshi.Json

/**
 * 
 *
 * @param isVisible 
 * @param listID 
 * @param partyID 
 * @param tasks 
 * @param type 
 */


data class CommonGetListInfoOut (

    @Json(name = "isVisible")
    val isVisible: kotlin.String? = null,

    @Json(name = "listID")
    val listID: kotlin.Int,

    @Json(name = "partyID")
    val partyID: kotlin.Int? = null,

    @Json(name = "tasks")
    val tasks: kotlin.collections.List<CommonTaskInfo>? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

)

