/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actionFrom id юзера, который удаляет
 * @param partyID 
 * @param userToDelete юзер которого удаляют
 */


data class CommonDeleteUserFromPartyIn (

    /* id юзера, который удаляет */
    @Json(name = "actionFrom")
    val actionFrom: kotlin.Int,

    @Json(name = "partyID")
    val partyID: kotlin.Int,

    /* юзер которого удаляют */
    @Json(name = "userToDelete")
    val userToDelete: kotlin.Int

)

