/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userCreatorID 
 * @param address 
 * @param addressAdditional 
 * @param addressLink 
 * @param coverID обложка, рандом изначально
 * @param dressCode 
 * @param endTime 
 * @param important 
 * @param isExpenses 0-3 4 разных состояния, клиент засылает
 * @param moodboadLink 
 * @param name 
 * @param startTime 
 * @param theme 
 */


data class CommonCreateEventIn (

    @Json(name = "userCreatorID")
    val userCreatorID: kotlin.Int,

    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "addressAdditional")
    val addressAdditional: kotlin.String? = null,

    @Json(name = "addressLink")
    val addressLink: kotlin.String? = null,

    /* обложка, рандом изначально */
    @Json(name = "coverID")
    val coverID: kotlin.Int? = null,

    @Json(name = "dressCode")
    val dressCode: kotlin.String? = null,

    @Json(name = "endTime")
    val endTime: kotlin.String? = null,

    @Json(name = "important")
    val important: kotlin.String? = null,

    /* 0-3 4 разных состояния, клиент засылает */
    @Json(name = "isExpenses")
    val isExpenses: kotlin.Int? = null,

    @Json(name = "moodboadLink")
    val moodboadLink: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "startTime")
    val startTime: kotlin.String? = null,

    @Json(name = "theme")
    val theme: kotlin.String? = null

)

