/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param newName 
 * @param taskID 
 */


data class CommonUpdateTaskNameIn (

    @Json(name = "newName")
    val newName: kotlin.String,

    @Json(name = "taskID")
    val taskID: kotlin.Int

)

