/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param hasDebitCard 
 * @param login 
 * @param profileImageID 
 * @param refreshToken 
 * @param userID 
 */


data class CommonLoginOut (

    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "hasDebitCard")
    val hasDebitCard: kotlin.Boolean,

    @Json(name = "login")
    val login: kotlin.String,

    @Json(name = "profileImageID")
    val profileImageID: kotlin.Int,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "userID")
    val userID: kotlin.Int

)

