/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.ozon.ozon_pvz.network.my.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param expenseID 
 * @param partyID 
 * @param userID 
 */


data class CommonGetUserExpenseInfoByIDIn (

    @Json(name = "expenseID")
    val expenseID: kotlin.Int,

    @Json(name = "partyID")
    val partyID: kotlin.Int,

    @Json(name = "userID")
    val userID: kotlin.Int

)

