/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param login 
 * @param profileImageID 
 * @param refreshToken 
 * @param userID 
 */


data class CommonRegisterOut (

    @Json(name = "AccessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "Login")
    val login: kotlin.String,

    @Json(name = "ProfileImageID")
    val profileImageID: kotlin.Int,

    @Json(name = "RefreshToken")
    val refreshToken: kotlin.String? = null,

    @Json(name = "UserID")
    val userID: kotlin.Int

)

