/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.linkav20.network.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param isVisible 
 * @param partyId 
 * @param type 
 */


data class CommonGetPartyListsOut (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "isVisible")
    val isVisible: kotlin.String? = null,

    @Json(name = "party_id")
    val partyId: kotlin.Int? = null,

    @Json(name = "type")
    val type: kotlin.String? = null

)

